nats:
  enabled: true
  auth:
    enabled: false
  client:
    service:
      type: NodePort
      nodePort: 30063

replicaCount: 1
image:
  repository: bookmanj/my-service
  tag: "latest"
service:
  port: 80
  type: ClusterIP
ingress:
  enabled: true
  host: my-service.local

job:
  enabled: true
  vars:
    - var:
        key: nats_server
        value: ""
    - var:
        key: nats_subject
        value: platform.my-dotnet-job-status
    - var:
        key: nats_start_msg
        value: "py-job start!"
    - var:
        key: nats_status_msg
        value: "Still working..."
    - var:
        key: nats_end_msg
        value: "py-job end!"


