apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Release.Name }}-{{ .Chart.Name }}
        env:
        #setting environment variables in the container (read from values.yaml)
        {{- range .Values.job.vars }}
        - name: {{ .var.key }}
          value: {{ .var.value }}
        {{- end }}
        ports:
        - name: frontend
          containerPort: 5000
        

